# -*- coding: utf-8 -*-
"""mikolaj.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1edBHQfNWeh9YII_vIkBRZV7ltOeX6Enc
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches
import streamlit as st

def generuj_figurę_mikolaja_z_workiem():
    """
    Generuje i zwraca obiekt Figure (figurę) stylizowanego rysunku
    Świętego Mikołaja z rękami i workiem na prezenty, za pomocą Matplotlib.

    Zwraca:
        matplotlib.figure.Figure: Obiekt figury Matplotlib.
    """

    # 1. Konfiguracja wykresu
    # Używamy plt.figure() zamiast plt.subplots(), aby figury Matplotlib
    # działały optymalnie ze st.pyplot w Streamlit.
    fig = plt.figure(figsize=(7, 8))
    ax = fig.add_subplot(111)

    # Ustawiamy limity osi i wyłączamy ich wyświetlanie
    ax.set_xlim(-1.5, 1.5)
    ax.set_ylim(-1.5, 1.5)
    ax.set_aspect('equal')
    ax.axis('off')

    # Kolory
    Czerwien_Mikołaja = '#C00000'
    Kolor_Skóry = '#FFDBB4'
    Biały_Brody = 'white'
    Złoty_Klamry = '#FFD700'
    Zieleń_Worka = '#006400'

    # --- 2. Rysowanie ciała i głowy ---

    # Ciało (czerwony owal)
    czerwony_korpus = patches.Ellipse(
        (0, -0.4),  # Środek
        0.9,        # Szerokość
        1.0,        # Wysokość
        color=Czerwien_Mikołaja,
        alpha=0.9,
        zorder=1
    )
    ax.add_patch(czerwony_korpus)

    # Głowa (skóra)
    skora_glowa = patches.Circle(
        (0, 0.45), # Środek
        0.25,      # Promień
        color=Kolor_Skóry,
        zorder=2
    )
    ax.add_patch(skora_glowa)

    # --- 3. Czapka ---

    # Czapka (czerwony stożek)
    czapka_czerwona = patches.Polygon(
        [(-0.30, 0.55), (0.30, 0.55), (0, 1.25)],
        color=Czerwien_Mikołaja,
        zorder=3
    )
    ax.add_patch(czapka_czerwona)

    # Czapka - futrzany brzeg (biały prostokąt)
    brzeg_czapki = patches.Rectangle(
        (-0.35, 0.50),
        0.7,
        0.1,
        color=Biały_Brody,
        zorder=4
    )
    ax.add_patch(brzeg_czapki)

    # Czapka - pompon (białe koło)
    pompon = patches.Circle(
        (0, 1.25),
        0.08,
        color=Biały_Brody,
        zorder=5
    )
    ax.add_patch(pompon)

    # --- 4. Broda i Twarz ---

    # Broda (duży biały owal)
    broda = patches.Ellipse(
        (0, 0.15),
        0.5,
        0.6,
        color=Biały_Brody,
        zorder=5
    )
    ax.add_patch(broda)

    # Nos (mniejszy czerwony okrąg)
    nos = patches.Circle(
        (0, 0.38),
        0.06,
        color='red',
        zorder=6
    )
    ax.add_patch(nos)

    # Oczy (małe czarne kropki)
    lewe_oko = patches.Circle((-0.12, 0.48), 0.03, color='black', zorder=7)
    prawe_oko = patches.Circle((0.12, 0.48), 0.03, color='black', zorder=7)
    ax.add_patch(lewe_oko)
    ax.add_patch(prawe_oko)

    # --- 5. Pas ---

    # Pas (czarny prostokąt)
    pas = patches.Rectangle(
        (-0.45, -0.05),
        0.9,
        0.15,
        color='black',
        zorder=6
    )
    ax.add_patch(pas)

    # Klamra pasa (żółty/złoty kwadrat)
    klamra = patches.Rectangle(
        (-0.12, -0.025),
        0.24,
        0.1,
        color=Złoty_Klamry,
        zorder=7
    )
    ax.add_patch(klamra)

    # --- 6. Ręce i Worek ---

    # Ręka Prawa (po lewej stronie wizualnie)
    prawy_rękaw = patches.Rectangle(
        (-0.9, -0.5),
        0.3,
        0.2,
        angle=45,
        color=Czerwien_Mikołaja,
        zorder=2
    )
    ax.add_patch(prawy_rękaw)

    prawy_manżet = patches.Rectangle(
        (-0.7, -0.3),
        0.15,
        0.1,
        angle=45,
        color=Biały_Brody,
        zorder=3
    )
    ax.add_patch(prawy_manżet)

    prawa_rękawica = patches.Ellipse(
        (-0.55, -0.15),
        0.2,
        0.2,
        color=Biały_Brody,
        zorder=4
    )
    ax.add_patch(prawa_rękawica)


    # Ręka Lewa (po prawej stronie wizualnie, trzyma worek)
    lewy_rękaw = patches.Rectangle(
        (0.6, -0.4),
        0.3,
        0.2,
        angle=-45,
        color=Czerwien_Mikołaja,
        zorder=2
    )
    ax.add_patch(lewy_rękaw)

    lewy_manżet = patches.Rectangle(
        (0.7, -0.45),
        0.15,
        0.1,
        angle=-45,
        color=Biały_Brody,
        zorder=3
    )
    ax.add_patch(lewy_manżet)

    lewa_rękawica = patches.Ellipse(
        (0.85, -0.55),
        0.2,
        0.2,
        color=Biały_Brody,
        zorder=4
    )
    ax.add_patch(lewa_rękawica)

    # Worek na Prezenty
    worek = patches.Ellipse(
        (0.8, -0.8),
        0.5,
        0.8,
        angle=-10,
        color=Zieleń_Worka,
        zorder=1
    )
    ax.add_patch(worek)

    # Góra worka/Sznurek
    gora_worka = patches.Rectangle(
        (0.6, -0.65),
        0.4,
        0.08,
        angle=-10,
        color=Złoty_Klamry,
        zorder=2
    )
    ax.add_patch(gora_worka)


    ax.set_title("Święty Mikołaj z Workiem (Matplotlib)", fontsize=16)

    return fig

# --- Główna funkcja Streamlit ---

def main():
    """
    Główna funkcja aplikacji Streamlit.
    """
    st.title("🎅 Generator Świętego Mikołaja")
    st.write("Wizualizacja Mikołaja wykonana z użyciem biblioteki Matplotlib w aplikacji Streamlit.")

    # Wywołanie funkcji generującej figurę
    figura_mikolaja = generuj_figurę_mikolaja_z_workiem()

    # Wyświetlenie figury Matplotlib za pomocą Streamlit
    st.pyplot(figura_mikolaja)

if __name__ == "__main__":
    main()